# Generated by Django 3.1.4 on 2021-05-06 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20210506_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postText', models.TextField(verbose_name='post text')),
                ('postImage', models.ImageField(blank=True, null=True, upload_to='element/')),
                ('area', models.TextField(verbose_name='post area')),
                ('plot', models.TextField(verbose_name='post plotnum')),
                ('price', models.CharField(blank=True, max_length=15, null=True, verbose_name='price of item')),
                ('postby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postText', models.TextField(verbose_name='post text')),
                ('postImage', models.ImageField(blank=True, null=True, upload_to='element/')),
                ('area', models.TextField(verbose_name='post area')),
                ('plot', models.TextField(verbose_name='post plotnum')),
                ('price', models.CharField(blank=True, max_length=15, null=True, verbose_name='price of item')),
                ('age', models.TextField(max_length=6, verbose_name='age')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], max_length=1)),
                ('contactnum', models.CharField(blank=True, max_length=8, null=True, verbose_name='phone')),
                ('postby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
