# Generated by Django 3.1.4 on 2021-05-23 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_vacancypost_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancypost',
            name='createDate',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='date and time created'),
        ),
    ]
